import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: "../fonts/TBCXMedium.ttf" });
export const metadata: Metadata = {
  title: {
    template: "%s | My Market",
    default: "My Market | powered by Internship",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} min-h-screen transition-colors duration-300`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
