import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import localFont from "next/font/local";
import { UserActivityProvider } from "@/context/UserActivityContext";
import Provider from "@/utils/queryProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header/Header";

const myFont = localFont({
  src: "../../fonts/TBCXMedium.ttf",
  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | My Market",
    default: "My Market | powered by Internship",
  },
  description: "Generated by create next app",
  verification: {
    google: "xPMYc9V3SU191hoD-El7LTRp9GO9Q7IzxFKm-psgt4I",
  },
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({ children, params: { locale } }: Props) {
  return (
    <html lang={locale}>
      <body className={`${myFont.className} min-h-screen  `}>
        <UserActivityProvider>
          <Provider>
            <Header />

            {children}

            <Footer />
          </Provider>
          <Toaster
            position="top-center"
            gutter={12}
            containerStyle={{ margin: "8px" }}
            toastOptions={{
              success: {
                duration: 3000,
              },
              error: {
                duration: 3000,
              },
              style: {
                fontSize: "16px",
                maxWidth: "500px",
                padding: "16px 12px",
                backgroundColor: "white",
                color: "grey",
              },
            }}
          />
        </UserActivityProvider>
      </body>
    </html>
  );
}
